/* Core/Src/web_content.c — Embedded web UI stored as const arrays in flash */
#include "web_content.h"

/* ======================================================================
 * Dashboard page — live I/O status with auto-refresh
 * ====================================================================== */
const uint8_t web_index_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>BNS Board</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:12px}"
"h1{font-size:1.3em;color:#0ff;margin-bottom:8px}"
"nav{margin-bottom:12px}nav a{color:#0ff;margin-right:16px;text-decoration:none}"
".card{background:#16213e;border-radius:8px;padding:12px;margin-bottom:10px}"
".card h2{font-size:1em;color:#888;margin-bottom:6px}"
"table{width:100%;border-collapse:collapse}"
"td{padding:4px 8px;border-bottom:1px solid #222}"
"td:first-child{color:#aaa;width:40%}"
".on{color:#0f0;font-weight:bold}.off{color:#666}"
"button{background:#0a3d62;color:#fff;border:none;padding:6px 14px;border-radius:4px;cursor:pointer}"
"button:hover{background:#1e6ea1}"
".dirty{background:#a83;color:#fff;padding:4px 10px;border-radius:4px;margin-left:8px;font-size:0.85em}"
"#status{font-size:0.8em;color:#555;margin-top:8px}"
"</style></head><body>"
"<h1 id='devname'>BNS Board</h1>"
"<nav><a href='/'>Dashboard</a><a href='/settings'>Settings</a><a href='/apps'>Apps</a></nav>"
"<span id='dirtyBadge' class='dirty' style='display:none'>Unsaved Changes</span>"
"<div class='card'><h2>Digital Inputs</h2><table id='dinTbl'></table></div>"
"<div class='card'><h2>Digital Outputs</h2><table id='doutTbl'></table></div>"
"<div class='card' id='ainCard' style='display:none'><h2>Analog Inputs</h2><table id='ainTbl'></table></div>"
"<div class='card' id='aoutCard' style='display:none'><h2>Analog Outputs</h2><table id='aoutTbl'></table></div>"
"<div id='status'>Loading...</div>"
"<script>"
"function q(id){return document.getElementById(id)}"
"function poll(){"
"fetch('/status.json').then(r=>r.json()).then(d=>{"
"q('dirtyBadge').style.display=d.dirty?'inline':'none';"
"var h='';"
"d.din.forEach(function(io){h+='<tr><td>'+io.n+'</td><td class=\"'+(io.v?'on':'off')+'\">'+(io.v?'ON':'OFF')+'</td></tr>'});"
"q('dinTbl').innerHTML=h;"
"h='';"
"d.dout.forEach(function(io,i){h+='<tr><td>'+io.n+'</td><td class=\"'+(io.v?'on':'off')+'\">'+(io.v?'ON':'OFF')+"
"'</td><td><button onclick=\"tog('+i+')\">Toggle</button></td></tr>'});"
"q('doutTbl').innerHTML=h;"
"if(d.ain&&d.ain.length){q('ainCard').style.display='';h='';d.ain.forEach(function(io){h+='<tr><td>'+io.n+'</td><td>'+io.v+'</td></tr>'});q('ainTbl').innerHTML=h}"
"if(d.aout&&d.aout.length){q('aoutCard').style.display='';h='';d.aout.forEach(function(io){h+='<tr><td>'+io.n+'</td><td>'+io.v+'</td></tr>'});q('aoutTbl').innerHTML=h}"
"q('status').textContent='Last update: '+new Date().toLocaleTimeString();"
"}).catch(function(e){q('status').textContent='Connection error'})}"
"function tog(n){fetch('/toggle?num='+n).then(function(){poll()})}"
"fetch('/info.json').then(r=>r.json()).then(d=>{q('devname').textContent=d.device_name});"
"setInterval(poll,500);poll();"
"</script></body></html>";

const uint32_t web_index_html_len = sizeof(web_index_html) - 1;

/* ======================================================================
 * Settings page — configuration form with Save/Revert
 * ====================================================================== */
const uint8_t web_settings_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>BNS Settings</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:12px}"
"h1{font-size:1.3em;color:#0ff;margin-bottom:8px}"
"nav{margin-bottom:12px}nav a{color:#0ff;margin-right:16px;text-decoration:none}"
".card{background:#16213e;border-radius:8px;padding:12px;margin-bottom:10px}"
".card h2{font-size:1em;color:#888;margin-bottom:6px}"
"label{display:block;margin:6px 0 2px;color:#aaa;font-size:0.85em}"
"input[type=text],input[type=number]{width:100%;padding:6px;background:#0f3460;border:1px solid #333;color:#fff;border-radius:4px}"
"select{padding:6px;background:#0f3460;border:1px solid #333;color:#fff;border-radius:4px}"
"input[type=checkbox]{margin-right:6px}"
"button{background:#0a3d62;color:#fff;border:none;padding:8px 18px;border-radius:4px;cursor:pointer;margin:4px 4px 4px 0}"
"button:hover{background:#1e6ea1}"
".save-btn{background:#2d6a4f}.save-btn:hover{background:#40916c}"
".revert-btn{background:#6c3a2a}.revert-btn:hover{background:#a84432}"
".dirty{background:#a83;color:#fff;padding:4px 10px;border-radius:4px;font-size:0.85em}"
".msg{padding:6px;margin:6px 0;border-radius:4px;font-size:0.9em}"
".msg-ok{background:#2d6a4f}.msg-err{background:#6c3a2a}"
".io-grid{display:grid;grid-template-columns:50px 1fr 1fr 1fr auto;gap:4px;font-size:0.85em;align-items:center}"
".io-grid input[type=text]{width:100%;padding:3px}.io-grid label{white-space:nowrap}"
"</style></head><body>"
"<h1>Settings</h1>"
"<nav><a href='/'>Dashboard</a><a href='/settings'>Settings</a><a href='/apps'>Apps</a></nav>"
"<div id='msg'></div>"
"<div class='card'><h2>Device</h2>"
"<label>Device Name</label><input type='text' id='device_name' maxlength='31'>"
"<label><input type='checkbox' id='lcd_enabled'>LCD Enabled (Mama only)</label>"
"</div>"
"<div class='card'><h2>Network</h2>"
"<label>IP Mode</label><select id='ip_mode'><option value='0'>Static</option><option value='1'>DHCP</option></select>"
"<label>Static IP</label><input type='text' id='static_ip'>"
"<label>Subnet</label><input type='text' id='subnet'>"
"<label>Gateway</label><input type='text' id='gateway'>"
"<label>DNS</label><input type='text' id='dns'>"
"</div>"
"<div class='card'><h2>MQTT</h2>"
"<label><input type='checkbox' id='mqtt_enabled'>Enable MQTT</label>"
"<label>Broker Host</label><input type='text' id='mqtt_broker_host' maxlength='63'>"
"<label>Broker Port</label><input type='number' id='mqtt_broker_port'>"
"<label>Username</label><input type='text' id='mqtt_username' maxlength='31'>"
"<label>Password</label><input type='text' id='mqtt_password' maxlength='31'>"
"<label>Root Topic</label><input type='text' id='mqtt_root_topic' maxlength='63'>"
"<label><input type='checkbox' id='mqtt_append_node_id'>Append Node ID</label>"
"<label>Client ID Prefix</label><input type='text' id='mqtt_client_id_prefix' maxlength='15'>"
"<label>Keep-alive (sec)</label><input type='number' id='mqtt_keepalive_sec'>"
"<label>Reconnect delay (ms)</label><input type='number' id='mqtt_reconnect_ms'>"
"<label>Analog publish interval (sec)</label><input type='number' id='mqtt_analog_interval_s'>"
"</div>"
"<div class='card'><h2>I/O Names &amp; MQTT Values</h2>"
"<div class='io-grid'><b></b><b>Name</b><b>ON Value</b><b>OFF Value</b><b>String?</b></div>"
"<div id='ioGrid'></div>"
"</div>"
"<button class='save-btn' onclick='saveToFlash()'>Save to Flash</button>"
"<button class='revert-btn' onclick='revert()'>Revert</button>"
"<button onclick='applyToRam()'>Apply (RAM only)</button>"
"<script>"
"var cfg={};"
"function q(id){return document.getElementById(id)}"
"function msg(t,ok){q('msg').innerHTML='<div class=\"msg '+(ok?'msg-ok':'msg-err')+'\">'+t+'</div>';setTimeout(function(){q('msg').innerHTML=''},3000)}"
"function load(){"
"fetch('/config.json').then(function(r){"
"if(!r.ok)throw new Error('HTTP '+r.status);"
"return r.json();"
"}).then(function(d){"
"cfg=d;"
"q('device_name').value=d.device_name||'';"
"q('lcd_enabled').checked=d.lcd_enabled;"
"q('ip_mode').value=d.ip_mode;"
"q('static_ip').value=d.static_ip||'';"
"q('subnet').value=d.subnet||'';"
"q('gateway').value=d.gateway||'';"
"q('dns').value=d.dns||'';"
"q('mqtt_enabled').checked=d.mqtt_enabled;"
"q('mqtt_broker_host').value=d.mqtt_broker_host||'';"
"q('mqtt_broker_port').value=d.mqtt_broker_port||1883;"
"q('mqtt_username').value=d.mqtt_username||'';"
"q('mqtt_password').value=d.mqtt_password||'';"
"q('mqtt_root_topic').value=d.mqtt_root_topic||'';"
"q('mqtt_append_node_id').checked=d.mqtt_append_node_id;"
"q('mqtt_client_id_prefix').value=d.mqtt_client_id_prefix||'';"
"q('mqtt_keepalive_sec').value=d.mqtt_keepalive_sec||60;"
"q('mqtt_reconnect_ms').value=d.mqtt_reconnect_ms||5000;"
"q('mqtt_analog_interval_s').value=d.mqtt_analog_interval_s||60;"
"var h='';var sec=['DIN','DIN','DIN','DIN','DIN','DIN','DIN','DIN','DIN','DIN','DIN','DIN',"
"'DOUT','DOUT','DOUT','DOUT','DOUT','DOUT','DOUT','DOUT',"
"'AIN','AIN','AIN','AIN','AOUT','AOUT'];"
"var si=['0','1','2','3','4','5','6','7','8','9','10','11',"
"'0','1','2','3','4','5','6','7','0','1','2','3','0','1'];"
"if(d.io)d.io.forEach(function(io,idx){"
"h+='<div class=\"io-grid\">'+"
"'<span style=\"color:#888;font-size:0.8em\">'+sec[io.i]+si[io.i]+'</span>'+"
"'<input data-i=\"'+io.i+'\" data-f=\"n\" value=\"'+(io.n||'')+'\" placeholder=\"name\">'+"
"'<input data-i=\"'+io.i+'\" data-f=\"on\" value=\"'+(io.on||'')+'\">'+"
"'<input data-i=\"'+io.i+'\" data-f=\"off\" value=\"'+(io.off||'')+'\">'+"
"'<label><input type=\"checkbox\" data-i=\"'+io.i+'\" data-f=\"str\"'+(io.str?' checked':'')+'>Str</label>'+"
"'</div>'});"
"q('ioGrid').innerHTML=h;"
"msg('Config loaded',true);"
"}).catch(function(e){msg('Load failed: '+e.message,false)})}"
"function gather(){"
"var o={"
"device_name:q('device_name').value,"
"lcd_enabled:q('lcd_enabled').checked,"
"ip_mode:parseInt(q('ip_mode').value),"
"static_ip:q('static_ip').value,"
"subnet:q('subnet').value,"
"gateway:q('gateway').value,"
"dns:q('dns').value,"
"mqtt_enabled:q('mqtt_enabled').checked,"
"mqtt_broker_host:q('mqtt_broker_host').value,"
"mqtt_broker_port:parseInt(q('mqtt_broker_port').value),"
"mqtt_username:q('mqtt_username').value,"
"mqtt_password:q('mqtt_password').value,"
"mqtt_root_topic:q('mqtt_root_topic').value,"
"mqtt_append_node_id:q('mqtt_append_node_id').checked,"
"mqtt_client_id_prefix:q('mqtt_client_id_prefix').value,"
"mqtt_keepalive_sec:parseInt(q('mqtt_keepalive_sec').value),"
"mqtt_reconnect_ms:parseInt(q('mqtt_reconnect_ms').value),"
"mqtt_analog_interval_s:parseInt(q('mqtt_analog_interval_s').value)"
"};"
"document.querySelectorAll('#ioGrid input,#ioGrid input[type=checkbox]').forEach(function(el){"
"var i=el.getAttribute('data-i'),f=el.getAttribute('data-f');"
"if(i!==null&&f){"
"var k='io_'+i+'_'+f;"
"o[k]=(el.type==='checkbox')?el.checked:el.value;"
"}});"
"return JSON.stringify(o)}"
"function applyToRam(){"
"fetch('/config.json',{method:'POST',headers:{'Content-Type':'application/json'},body:gather()})"
".then(r=>r.json()).then(d=>{if(d.ok)msg('Applied to RAM',true);else msg(d.error||'Error',false)})}"
"function saveToFlash(){"
"applyToRam();"
"setTimeout(function(){fetch('/config/save',{method:'POST'}).then(r=>r.json()).then(d=>{"
"if(d.ok)msg('Saved to flash!',true);else msg('Flash write failed',false)})},200)}"
"function revert(){"
"fetch('/config/revert',{method:'POST'}).then(r=>r.json()).then(d=>{if(d.ok){msg('Reverted',true);load()}})}"
"load();"
"</script></body></html>";

const uint32_t web_settings_html_len = sizeof(web_settings_html) - 1;

/* ======================================================================
 * Apps page — sequencer app status and controls
 * ====================================================================== */
const uint8_t web_apps_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>BNS Apps</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:12px}"
"h1{font-size:1.3em;color:#0ff;margin-bottom:8px}"
"nav{margin-bottom:12px}nav a{color:#0ff;margin-right:16px;text-decoration:none}"
".card{background:#16213e;border-radius:8px;padding:12px;margin-bottom:10px}"
".card h2{font-size:1em;margin-bottom:6px}"
".running{color:#0f0}.stopped{color:#f80}.empty{color:#555}"
"button{background:#0a3d62;color:#fff;border:none;padding:6px 14px;border-radius:4px;cursor:pointer;margin:2px}"
"button:hover{background:#1e6ea1}"
".mqtt-toggle{color:#0ff;cursor:pointer;font-size:0.85em;margin-left:8px}"
".mqtt-panel{display:none;margin-top:8px}"
".mqtt-panel.open{display:block}"
".mqtt-row{display:flex;gap:4px;margin-bottom:3px;align-items:center}"
".mqtt-row span{width:20px;color:#888;font-size:0.8em}"
".mqtt-row input{background:#0d1b2a;border:1px solid #333;color:#e0e0e0;padding:3px 6px;border-radius:3px;font-size:0.85em}"
".mqtt-row input.topic{flex:2}.mqtt-row input.payload{flex:1}"
"</style></head><body>"
"<h1>Sequencer Apps</h1>"
"<nav><a href='/'>Dashboard</a><a href='/settings'>Settings</a><a href='/apps'>Apps</a></nav>"
"<div id='appList'></div>"
"<script>"
"var mqttData={};"
"function poll(){"
"fetch('/status.json').then(r=>r.json()).then(d=>{"
"var h='';d.apps.forEach(function(a,i){"
"var state=a.nl==0?'empty':a.r?'running':'stopped';"
"var label=a.nl==0?'Empty':a.r?'Running (line '+a.l+'/'+a.nl+')':'Stopped ('+a.nl+' lines)';"
"h+='<div class=\"card\"><h2>App '+i+' <span class=\"'+state+'\">'+label+'</span>';"
"h+='<span class=\"mqtt-toggle\" onclick=\"toggleMqtt('+i+')\">[MQTT Table]</span></h2>';"
"if(a.nl>0){h+='<button onclick=\"appCtl('+i+',\\\"start\\\")\">Start</button>';"
"h+='<button onclick=\"appCtl('+i+',\\\"stop\\\")\">Stop</button>'}"
"h+='<div class=\"mqtt-panel\" id=\"mqtt'+i+'\">';"
"for(var e=0;e<8;e++){"
"var t=mqttData[i]&&mqttData[i][e]?mqttData[i][e].t:'';"
"var p2=mqttData[i]&&mqttData[i][e]?mqttData[i][e].p:'';"
"h+='<div class=\"mqtt-row\"><span>'+e+'</span>';"
"h+='<input class=\"topic\" id=\"mt'+i+'_'+e+'\" placeholder=\"topic\" value=\"'+t+'\">';"
"h+='<input class=\"payload\" id=\"mp'+i+'_'+e+'\" placeholder=\"payload\" value=\"'+p2+'\">';"
"h+='</div>'}"
"h+='<button onclick=\"saveMqtt('+i+')\">Save MQTT Table</button></div>';"
"h+='</div>'});"
"q('appList').innerHTML=h})}"
"function q(id){return document.getElementById(id)}"
"function appCtl(n,cmd){fetch('/app/'+n+'/'+cmd,{method:'POST'}).then(function(){poll()})}"
"function toggleMqtt(n){var el=q('mqtt'+n);if(el)el.classList.toggle('open')}"
"function loadMqtt(n){"
"fetch('/app/'+n+'/mqtt').then(r=>r.json()).then(d=>{"
"mqttData[n]={};d.entries.forEach(function(e){mqttData[n][e.i]={t:e.t,p:e.p}})})}"
"function saveMqtt(n){"
"var entries=[];"
"for(var e=0;e<8;e++){"
"var t=q('mt'+n+'_'+e).value;"
"var p2=q('mp'+n+'_'+e).value;"
"entries.push({i:e,t:t,p:p2})}"
"fetch('/app/'+n+'/mqtt',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({entries:entries})}).then(function(){loadMqtt(n)})}"
"for(var i=0;i<4;i++)loadMqtt(i);"
"setInterval(poll,1000);poll();"
"</script></body></html>";

const uint32_t web_apps_html_len = sizeof(web_apps_html) - 1;
